spring:
  application:
    name:
      auth-service
  datasource:
    driver-class-name: org.postgresql.Driver
  config:
    import: optional:configserver:${CONFIG_SERVER:http://localhost:8889/}
  main:
    allow-bean-definition-overriding: true
server:
  port: 8045
springdoc:
  api-docs:
    path: /api-docs